title: Department 99
description: Research, writing, and experiments.

url: "https://kitolomewa.github.io"
baseurl: ""

author:
  name: Kito Lomewa

markdown: kramdown

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
